### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by masterzxz** [wtfuii/TSOBot#2]
Upon executing npm start, I get the following output:

```

> tsobot@1.0.3 start /volume1/local/node_modules/tsobot
> node main-compiled.js

/volume1/local/node_modules/tsobot/node_modules/node-telegram-bot-api/src/telegram.js:29
class TelegramBot extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/volume1/local/node_modules/tsobot/node_modules/node-telegram-bot-api/index.js:12:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Linux 3.10.77
npm ERR! argv "/volume1/@appstore/Node.js_v4/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! tsobot@1.0.3 start: `node main-compiled.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tsobot@1.0.3 start script 'node main-compiled.js'.
npm ERR! This is most likely a problem with the tsobot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main-compiled.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tsobot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls tsobot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /volume1/local/node_modules/tsobot/npm-debug.log
```

Please assist.

**Comment by masterzxz** [comment]
@wtfuii can you please assist?

**Comment by wtfuii** [comment]
Hey, I didn't run into this upto now. Can you try to run node in strict mode? `node --use_strict main-compiled.js`

**Comment by masterzxz** [comment]
@wtfuii that gives the following output:

````
ash-4.3# npm start

> tsobot@1.0.3 start /volume1/local/node_modules/tsobot
> node --use_strict main-compiled.js

/volume1/local/node_modules/tsobot/node_modules/node-telegram-bot-api/src/telegram.js:71
  constructor(token, options = {}) {
                             ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/volume1/local/node_modules/tsobot/node_modules/node-telegram-bot-api/index.js:12:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Linux 3.10.77
npm ERR! argv "/volume1/@appstore/Node.js_v4/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! tsobot@1.0.3 start: `node --use_strict main-compiled.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tsobot@1.0.3 start script 'node --use_strict main-compiled.js'.
npm ERR! This is most likely a problem with the tsobot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --use_strict main-compiled.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tsobot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls tsobot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /volume1/local/node_modules/tsobot/npm-debug.log
```
`

**Comment by wtfuii** [comment]
Can you please try to upgrade your version of node.js to the latest version 7.4.0?
